version: '3'
services: 
    web:
        build: .
        ports: 
            - 80:80
        restart: "on-failure"
        environment: 
            - NODE_ENV=docker
    mongo:
        image: "mongo:bionic"
        restart: "always"